version: "3.8"
services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - nodemodules:/usr/src/hnnazm/node_modules
      - ./:/usr/src/hnnazm
    ports:
      - 3000:3000
    command: npm run start
volumes:
  nodemodules:
